[package]
name = "optimized_minecraft"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glfw = "0.47.0"
glam = "0.24.0"
image = "0.24"
noise = "0.8"
rand = "0.8"

[build-dependencies]
winres = "0.1"